### ISSUE TITLE
Troubles with the decimal point

### ISSUE THREAD

**Issue by rafaellop** [mrchandoo/cordova-plugin-decimal-keyboard#1]
They keyboard would be great but unfortunately it doesn't allow to use the decimal. I can show the decimal keyboard for the following code:

`<input type="text" decimal="true" pattern="[0-9]*" />`

but if I use a different pattern like this:

`<input type="text" decimal="true" pattern="[0-9.,]*" />`

it starts to show a normal text keyboard instead of the numerical + decimal. The text keyboard in that case contains the decimal button, but I don't want all these a-zA-Z characters in the keyboard. Just the simple numers + decimal point.

I've tried different patterns as well like `\d+(\.\d*)?` but still only text keyboard is shown in that case. Can you please help with this?

Why I ask? It's because if I use the `[0-9]*` pattern the entered value (like e.g. 89.5) from the decimal keyboard doesn't fit the pattern at the html side and my `ng-model` isn't updated.

**Comment by mrchandoo** [comment]
any other pattern apart from [0-9]* results in a text keypad on iOS, this has nothing to do with the plugin but to do with iOS.
the workaround in your case is to use find element in your directive and get value, instead of getting it from ngModel and use novalidate incase you are using any validators.

**Comment by rafaellop** [comment]
Pitty that it cannot be resolved at the plugin side. I catch the value in a custom directive and I'm able to assign it manually. Thanks for your reply and the suggestion.

**Comment by elineopsommer** [comment]
There are also troubles with the form validating, when you use this within a form, you cannot submit it
