### ISSUE TITLE
ng-model removed?

### ISSUE THREAD

**Issue by gehirnmitei** [mrchandoo/cordova-plugin-decimal-keyboard#10]
Ionic v1
Angular 1.5.3
I'm using this plugin on input with ng-model Attribute, but somehow this Attribute seems to get lost.

My workaround was to access the value of the input through the DOM Element, but i don't understand why scope.XXX is't working.

**Comment by kas84** [comment]
I believe this is due to ```pattern="[0-9]*"```. When you type 15.32, for example, it doesn't comply that pattern and model gets undefined. What I've done is wrap it in a directive and listen to blur events to set the model.

**Comment by mrchandoo** [comment]
Yep, once you use pattern with angular the component doesn't work, i have initially posted few responses for the same
