### ISSUE TITLE
Not working with cordova-plugin-wkwebview-engine 

### ISSUE THREAD

**Issue by CooleyGit** [mrchandoo/cordova-plugin-decimal-keyboard#2]
Just tried to run it and got error at the line below guessing its because im using wkwebview?

```
int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate"); 
```

This is a much needed plugin thanks for taking the time to build it. Let me know if you need more feedback or testing if you get it running in wkwebview.

**Comment by mrchandoo** [comment]
@CooleyGit the above piece of code is not from the plugin and this plugin is not tested on wkwebview.

i will try to do a sample with wkwebview and let you know.

**Comment by CooleyGit** [comment]
Cool thanks, not sure what was causing it then this was the only error I was seeing in Xcode.

**Comment by mrchandoo** [comment]
@CooleyGit i have tested it with the below plugins
cordova-plugin-decimal-keyboard 1.0 "Decimal Keyboard"
cordova-plugin-wkwebview-engine 1.1.3 "Cordova WKWebView Engine"
ios@4.0.0 and it is working fine 
<img width="319" alt="wkwebview" src="https://cloud.githubusercontent.com/assets/12436218/25831962/7b40f7d4-345f-11e7-87bb-8039853b84c0.png">

**Comment by mrchandoo** [comment]
Unable to reproduce the issue

**Comment by CooleyGit** [comment]
Sorry I should have provided more context im using ionic 2 well ionic 3.1.1 and have tried almost everything to get it to work but no luck. Can you provide a more detailed example of how this plugin should be used?

**Comment by mrchandoo** [comment]
Please remove the plugin from your command using cordova plugin remove cordova-plugin-decimal-keyboard 
build your cordova app to see if you get the same issue, if you get the same issue then i think there is no issue with the plugin but some problem with you code. good luck.

**Comment by CooleyGit** [comment]
Thanks, but I removed this plugin from my app as soon as I added it and it crashed my app... Then I created a blank Ionic app with a single input and your plugin. App crashes when the input is focused so it seems to be your plugin is not compatible with ionic anyway thanks for taking the time ill just have to figure something else out for now.
