### ISSUE TITLE
Enter Button

### ISSUE THREAD

**Issue by ZeroQool007** [mrchandoo/cordova-plugin-decimal-keyboard#21]
Where is the ENTER Button to close the keyboard?

**Comment by bharned3** [comment]
Ditto. I would love to have this as well...

I did something like this below in an app with swift. Maybe you can leverage this.

In view did load add this


addDoneButton()


Add this function to your view controller

 func addDoneButton() {
        let keyboardToolbar = UIToolbar()
            keyboardToolbar.sizeToFit()
        let flexBarButton = UIBarButtonItem(barButtonSystemItem: .FlexibleSpace,target: nil, action: nil)
        //let doneBarButton = UIBarButtonItem(barButtonSystemItem: .Done,target: view, action: Selector("endEditing:"))
//“didTapView” is the funtion to close keyboard or you can try the end editing above
        let doneBarButton = UIBarButtonItem(barButtonSystemItem: .Done,target: self, action: "didTapView")
        keyboardToolbar.items = [flexBarButton, doneBarButton]
//original price will be the name of your text field
        originalPrice.inputAccessoryView = keyboardToolbar
  }

**Comment by mrchandoo** [comment]
use ionic keyboard and either show or hide the done button based on the route you are
