### ISSUE TITLE
Allow-multiple-decimals="false" with decimal-char=","

### ISSUE THREAD

**Issue by martinmildner** [mrchandoo/cordova-plugin-decimal-keyboard#5]
Hi mrchandoo,
when using _allow-multiple-decimals="false"_ and _decimal-char=","_ the user is still able to enter multiple decimals.
greetings, martin

**Comment by rachelpopa** [comment]
Hi mrchandoo,

I am seeing the same thing when decimal-char is set to "-".  Thanks!

**Comment by mrchandoo** [comment]
its a bug and i fixed it, please take the latest version.
